name: Build Turnip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      TERM: xterm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            clang \
            llvm \
            lld \
            cmake \
            ninja-build \
            pkg-config \
            patchelf \
            python3 \
            python3-pip \
            python3-venv \
            python3-mako \
            python-is-python3 \
            flex \
            bison \
            glslang-tools \
            vulkan-tools \
            unzip \
            zip \
            wget \
            curl \
            git \
            ccache

      - name: Install Latest Meson
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "meson>=1.5.0"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Environment Info
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          echo "===== SYSTEM ====="
          uname -a

          echo "===== MESON ====="
          which meson
          meson --version

          echo "===== CLANG ====="
          clang --version

          echo "===== NINJA ====="
          ninja --version

      - name: Make build script executable
        run: chmod +x build-turnip.sh

      - name: Run Build Script
        run: |
          export TERM=xterm
          export PATH="$HOME/.local/bin:$PATH"
          set -ex
          ./build-turnip.sh

      - name: Show Output Files
        if: always()
        run: |
          echo "===== GENERATED FILES ====="
          find . -name "*.zip"
          find . -name "*.so"
          find . -name "meson_log"
          find . -name "meson-log.txt"
          find . -name "ninja_log"

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Logs
          path: |
            **/meson_log
            **/meson-log.txt
            **/ninja_log

      - name: Upload Turnip Driver
        uses: actions/upload-artifact@v4
        with:
          name: Turnip-Driver
          path: |
           turnip_workdir/*EMULATOR.zip
