name: Build Turnip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      TERM: xterm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            build-essential \
            clang \
            llvm \
            lld \
            cmake \
            meson \
            ninja-build \
            pkg-config \
            patchelf \
            python3 \
            python3-pip \
            python3-venv \
            python3-mako \
            python-is-python3 \
            flex \
            bison \
            glslang-tools \
            vulkan-tools \
            unzip \
            zip \
            wget \
            curl \
            git \
            ccache

      - name: Environment Info
        run: |
          echo "===== SYSTEM ====="
          uname -a

          echo "===== CLANG ====="
          clang --version

          echo "===== MESON ====="
          meson --version

          echo "===== NINJA ====="
          ninja --version

          echo "===== CMAKE ====="
          cmake --version

          echo "===== PKG-CONFIG ====="
          pkg-config --version

          echo "===== CCACHE ====="
          ccache --version

      - name: Make build script executable
        run: chmod +x build-turnip.sh

      - name: Run Build Script
        run: |
          set -ex
          ./build-turnip.sh

      - name: Show Output Files
        if: always()
        run: |
          echo "===== GENERATED FILES ====="
          find . -name "*.zip"
          find . -name "*.so"
          find . -name "meson-log.txt"

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Logs
          path: |
            **/meson_log
            **/meson-log.txt
            **/ninja_log

      - name: Upload Driver
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Turnip
          path: |
            **/*.zip
            **/*.so
